### PR TITLE
Move CSS and JS into seperate files 

### LINKED ISSUE #2: Move CSS and JS into separate files
Simply move what's inside the style and script tags in index.html into their own files, and link to those in index.html.

### PR DESCRIPTION
**Pull request by tharikashree**
Resolves #2 

# Changes

 - Move CSS and JS into Separate files 
-Added link to CSS file.
 `<link rel="stylesheet" href="styles.css">`
-Added link to the JS file.
`<script src="index.js"></script>`
-Moved the styles to styles.css file.
-Moved the script to index.js file.

### CODE REVIEW

**Comment by tharikashree** [comment]
@CappeSun 
Can you kindly add the hacktober-accepted label ,review and merge and the pr?

**Comment by CappeSun** [comment]
Sorry, could you instead of editing pull_request_template.md, change the the pull request description? As well as replace the text below 'Changes' with the changes you've made, and put the issue (number) the pull request solves after 'Resolves' at the top. Sorry it was unclear, I think you can simply edit this pull request by discarding the changes to pull_request_template.md and updating the description and all should be good

**Comment by tharikashree** [comment]
@CappeSun 
Yeah sure will do.
Sorry for the mix up
I have made the changes to the description as you asked.
I had reverted the pull_request_template.md in my latest commit.
can you kindly review it ?

**Review by CappeSun — APPROVED** [review]
All good!

**Comment by CappeSun** [comment]
Reviewed and merged, thank you!

**Comment by tharikashree** [comment]
Thank you for assigning me !!!

**Pull request merged**
